export const SERVICES_REQUEST = "SERVICES_REQUEST";
export const FETCH_SERVICES_SUCCESS = "FETCH_SERVICES_SUCCESS";
export const FETCH_SERVICES_FAILURE = "FETCH_SERVICES_FAILURE";
export const ADD_SERVICE_VALUE = "ADD_SERVICE_VALUE";
export const FETCH_SERVICE_ITEM = "FETCH_SERVICE_ITEM";
